### ISSUE TITLE
Init scripts causing error - grep: Unmatched ( or \(

### ISSUE THREAD

**Issue by aSemy** [bitnami/bitnami-docker-cassandra#69] opened 2020-04-15 09:38 UTC
**Description**

I want to initialise Cassandra with some scripts. I followed the [instructions here](https://github.com/bitnami/bitnami-docker-cassandra#initializing-with-custom-scripts) and mounted a folder containing one script.

Note that without the line `      - "./init:/docker-entrypoint-initdb.d"` the container starts with no errors.

**Steps to reproduce the issue:**

<details>
<summary>

 `docker-compose.yml` 

</summary>

```yml
version: '3.7'
services:
  cassandra:
    image: "bitnami/cassandra:latest"
    container_name: "cassandra"
    hostname: "localhost"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    volumes:
      - "./data:/bitnami"
      - "./init:/docker-entrypoint-initdb.d"
```

</details>

<details>
<summary>

`01_keyspace.cql`

</summary>

```cql
CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

USE test;
```

</details>

1. Run `docker-compose up`
2. View logs

**Describe the results you received:**

<details>
<summary>

`docker logs cassandra`

</summary>

```zsh
cassandra 11:54:48.03 
cassandra 11:54:48.04 Welcome to the Bitnami cassandra container
cassandra 11:54:48.04 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-cassandra
cassandra 11:54:48.04 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-cassandra/issues
cassandra 11:54:48.04 Send us your feedback at containers@bitnami.com
cassandra 11:54:48.05 
cassandra 11:54:48.05 INFO  ==> ** Starting Cassandra setup **
cassandra 11:54:48.08 INFO  ==> Validating settings in CASSANDRA_* env vars..
cassandra 11:54:48.08 WARN  ==> You set the environment variable CASSANDRA_PASSWORD=cassandra. This is the default value when bootstrapping Cassandra and should not be used in production environments.
cassandra 11:54:48.13 INFO  ==> Initializing Cassandra database...
cassandra 11:54:48.17 DEBUG ==> No injected cassandra-env.ps1 file found. Creating default cassandra-env.ps1 file
cassandra 11:54:48.19 DEBUG ==> No injected cassandra-rackdc.properties file found. Creating default cassandra-rackdc.properties file
cassandra 11:54:48.21 DEBUG ==> No injected cassandra-topology.properties file found. Creating default cassandra-topology.properties file
cassandra 11:54:48.22 DEBUG ==> No injected README.txt file found. Creating default README.txt file
cassandra 11:54:48.24 DEBUG ==> No injected logback-tools.xml file found. Creating default logback-tools.xml file
cassandra 11:54:48.25 DEBUG ==> No injected cqlshrc.sample file found. Creating default cqlshrc.sample file
cassandra 11:54:48.26 DEBUG ==> No injected metrics-reporter-config-sample.yaml file found. Creating default metrics-reporter-config-sample.yaml file
cassandra 11:54:48.28 DEBUG ==> No injected hotspot_compiler file found. Creating default hotspot_compiler file
cassandra 11:54:48.29 DEBUG ==> No injected commitlog_archiving.properties file found. Creating default commitlog_archiving.properties file
cassandra 11:54:48.30 DEBUG ==> No injected cassandra-env.sh file found. Creating default cassandra-env.sh file
cassandra 11:54:48.32 DEBUG ==> No injected jvm.options file found. Creating default jvm.options file
cassandra 11:54:48.34 DEBUG ==> No injected triggers/README.txt file found. Creating default triggers/README.txt file
cassandra 11:54:48.35 DEBUG ==> No injected cassandra.yaml file found. Creating default cassandra.yaml file
cassandra 11:54:48.36 DEBUG ==> No injected logback.xml file found. Creating default logback.xml file
cassandra 11:54:48.37 DEBUG ==> No injected cassandra-jaas.config file found. Creating default cassandra-jaas.config file
cassandra 11:54:48.54 DEBUG ==> Ensuring expected directories/files exist...
cassandra 11:54:48.57 INFO  ==> Deploying Cassandra from scratch
cassandra 11:54:48.57 INFO  ==> Starting Cassandra
cassandra 11:54:48.58 INFO  ==> Checking that it started up correctly
cassandra 11:54:48.58 DEBUG ==> Checking that log /opt/bitnami/cassandra/logs/cassandra_first_boot.log contains entry "Starting listening for CQL clients"
INFO  [main] 2020-04-15 11:54:58,739 Server.java:159 - Starting listening for CQL clients on /0.0.0.0:9042 (unencrypted)...
cassandra 11:55:03.62 INFO  ==> Found CQL startup log line
cassandra 11:55:03.62 DEBUG ==> Checking status with nodetool
grep: Unmatched ( or \(
grep: Unmatched ( or \(
grep: Unmatched ( or \(
grep: Unmatched ( or \(
grep: Unmatched ( or \(
cassandra 11:55:34.95 ERROR ==> Cassandra failed to start up
cassandra 11:55:34.96 ERROR ==> Nodetool output
```

</details>

**Describe the results you expected:**

Cassandra starts and the the scripts are run without error.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

<details>
<summary>

`docker version`

</summary>

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

</details>

<details>
<summary>

`docker info`

</summary>

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: XI42:FLMC:5TCU:SB3Q:F5RP:K6G4:QAD5:2FK7:QM23:IMBZ:4JKL:ENAV
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 51
  Goroutines: 64
  System Time: 2020-04-15T09:16:25.849667161Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

</details>

<details>
<summary>

`docker-compose version` 
</summary>
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```
</details>

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

MacOS version:

<details>
<summary>

`system_profiler SPSoftwareDataType`

</summary>

```
Software:

    System Software Overview:

      System Version: macOS 10.14.4 (18E227)
      Kernel Version: Darwin 18.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: ****
      User Name: ****
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 19:33

```

</details>

**Comment by marcosbc** [comment] 2020-04-16 14:45
We're unable to reproduce this issue, it works fine for us. We made the changes below to the docker-compose that is shown in the root of this repository:

```
--- docker-compose.yml.orig	2020-04-16 16:42:12.085917581 +0200
+++ docker-compose.yml	2020-04-16 16:42:22.010196114 +0200
@@ -7,8 +7,10 @@
       - '7000:7000'
       - '9042:9042'
     volumes:
+      - /home/bitnami/initscripts/initscripts:/docker-entrypoint-initdb.d
       - 'cassandra_data:/bitnami'
     environment:
+      - BITNAMI_DEBUG=true
       - CASSANDRA_SEEDS=cassandra
       - CASSANDRA_PASSWORD_SEEDER=yes
       - CASSANDRA_PASSWORD=cassandra
```

And the `/home/bitnami/initscripts/initscripts` directory contains a .cql file with the contents below:

```
CREATE KEYSPACE mykeyspace WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': 1}; DESCRIBE KEYSPACES;
```

When starting the Compose setup we see it is working properly:

```
cassandra_1  | cassandra 14:43:01.88 DEBUG ==> Executing /docker-entrypoint-initdb.d/keyspace.cql
cassandra_1  | cassandra 14:43:01.89 DEBUG ==> Executing CQL "CREATE KEYSPACE mykeyspace WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': 1}; DESCRIBE KEYSPACES;"
cassandra_1  |
cassandra_1  | system_schema  system      system_distributed
cassandra_1  | system_auth    mykeyspace  system_traces
cassandra_1  |
```

Could it be possible there is a typo in your .cql script?

**Comment by aSemy** [comment] 2020-04-22 09:17
Thanks for looking into it. I've tried again and it's working now that I've set the environment variables that you used. I really appreciate your response.

While obviously it was a configuration error on my part, if I can make a couple of suggestions: it would have helped to have the example being more complete, and have more descriptive error messages - from what I can make out `grep: Unmatched ( or \(` is not related to the init scripts but something else.

**Comment by marcosbc** [comment] 2020-04-22 17:01
We're unsure whether it could be init-script related or not, if they contained a grep the error is likely to be there. However, if you find a similar issue again please let us know.

As for the documentation, if you have any suggestions on how to improve it feel free to send a PR, we would be glad to review it!

**Comment by kkosewski** [comment] 2020-12-14 13:33
Him
not sure whether I should open new issue, but I'm having similar grep issues.
We are trying to use image cassandra:3.11.9-debian-10-r27 (tried also with r23) in our dual stack kubernetes environment.
Unfortunately image initialization is failing - in dual stack environment, container is obtaining 2 IPs: 1 IPv4 and 1 IPv6.
Seems like wait_for_nodetool_up function from /opt/bitnami/scripts/libcassandra.sh is having problems handling such situation.

And here we have our: grep: Unmatched ( or \(.
Log:
```
[...]
INFO  [main] 2020-12-14 12:12:26,412 Server.java:159 - Starting listening for CQL clients on /0.0.0.0:9042 (unencrypted)...
cassandra 12:12:35.09 INFO  ==> Found CQL startup log line
cassandra 12:12:35.11 DEBUG ==> Checking status with nodetool
grep: Unmatched ( or \(
grep: Unmatched ( or \(
grep: Unmatched ( or \(
cassandra 12:16:41.41 ERROR ==> Cassandra failed to start up
cassandra 12:16:41.42 ERROR ==> Nodetool output
```

After adding 'set -x' in code of this function:
```
[...]
INFO  [main] 2020-12-14 11:44:53,150 Server.java:159 - Starting listening for CQL clients on /0.0.0.0:9042 (unencrypted)...
cassandra 11:45:17.64 INFO  ==> Found CQL startup log line
+ debug 'Checking status with nodetool'
+ local bool=true
+ shopt -s nocasematch
+ [[ true = 1 ]]
+ [[ true =~ ^(yes|true)$ ]]
+ log '\033[38;5;5mDEBUG\033[0m ==> Checking status with nodetool'
++ date '+%T.%2N '
+ stderr_print '\033[38;5;6mcassandra \033[38;5;5m11:45:17.65 \033[0m\033[38;5;5mDEBUG\033[0m ==> Checking status with nodetool'
+ local bool=false
+ shopt -s nocasematch
+ [[ false = 1 ]]
+ [[ false =~ ^(yes|true)$ ]]
+ printf '%b\n' '\033[38;5;6mcassandra \033[38;5;5m11:45:17.65 \033[0m\033[38;5;5mDEBUG\033[0m ==> Checking status with nodetool'
cassandra 11:45:17.65 DEBUG ==> Checking status with nodetool
+ retry_while check_function_nodetool 60 60
+ local cmd=check_function_nodetool
+ local retries=60
+ local sleep_time=60
+ local return_value=1
+ read -r -a command
+ (( i = 1  ))
+ (( i <= retries  ))
+ check_function_nodetool
+ check_cmd=("${CASSANDRA_BIN_DIR}/nodetool")
+ local -r check_cmd
+ check_args=("status" "--port" "$CASSANDRA_JMX_PORT_NUMBER")
+ local -r check_args
++ dns_lookup dev-portal-cassandra-857b8d9665-z78ns
++ local host=dev-portal-cassandra-857b8d9665-z78ns
++ getent ahosts dev-portal-cassandra-857b8d9665-z78ns
++ awk '/STREAM/ {print $1 }'
+ local -r 'machine_ip=fd00:100::b47f
10.242.180.127'
+ local -r 'check_regex=UN\s*(dev-portal-cassandra-857b8d9665-z78ns|fd00:100::b47f
10.242.180.127|127.0.0.1)'
+ local output=/dev/null
+ [[ true = \t\r\u\e ]]
+ output=/dev/stdout
+ /opt/bitnami/cassandra/bin/nodetool status --port 7199
+ grep -E 'UN\s*(dev-portal-cassandra-857b8d9665-z78ns|fd00:100::b47f
10.242.180.127|127.0.0.1)'
grep: Unmatched ( or \(
```

Looks like ${machine_ip} var value is : fd00:100::b47f
10.242.180.127
Grep is not able to handle such case.
Would be good if machine_ip var is handled in a way that it is returning only 1 IP.
I think similar issue is described here:
https://github.com/docker-library/cassandra/issues/56

In my case hostname --ip-address also returns 2 addresses.
fd00:100::b440 10.242.180.64

**Comment by marcosbc** [comment] 2020-12-15 15:46
Hi @kkosewski, it looks like indeed there is an issue with the `wait_for_nodetool_up` function due to `dns_lookup` showing multiple IP addresses. This is the problematic function: [libnet.sh#L21](https://github.com/bitnami/bitnami-docker-cassandra/blob/master/3/debian-10/prebuildfs/opt/bitnami/scripts/libnet.sh#L21).

We could probably fix this by changing the following line, since in the end we're expecting to get only one IP address:

```diff
-getent ahosts "$host" | awk '/STREAM/ {print $1 }'
+getent ahosts "$host" | awk '/STREAM/ {print $1 }' | head -n 1
```

What do you think?

**Comment by kkosewski** [comment] 2020-12-16 01:49
Hi @marcosbc, this solution doesn't work for me - here is why:
`getent ahosts "$host" | awk '/STREAM/ {print $1 }'` returns 2 IP addresses in my case:
```
I have no name!@dev-portal-cassandra-56c6dc74d6-hln8g:/$ getent ahosts dev-portal-cassandra-56c6dc74d6-hln8g | awk '/STREAM/ {print $1 }'
fd00:100::b46b
10.242.180.107
```

So after `head -n 1` I get only IPv6 as it is returned as first address.
And as it seems that `nodetool status --port 7199` shows only IPv4, grep from `wait_for_nodetool_up` will not catch it, right?
I would prefer something like `grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"` instead of `head -n 1`, if it's not a problem.

**Comment by marcosbc** [comment] 2020-12-16 08:53
Hi @kkosewski, in that case, maybe you'd want the following?

    getent ahostsv4 "$host" | awk '/STREAM/ {print $1 }' | head -n 1

(adding "head -n 1" to avoid issues with multiple public IP addresses)

**Comment by kkosewski** [comment] 2020-12-16 09:08
Hi @marcosbc, this is fine - works for me.

**Comment by marcosbc** [comment] 2020-12-16 17:37
Hi, just a note that we're expecting to release `3.11.9-debian-10-r30` later today, which includes a fix for this issue.

**Comment by marcosbc** [comment] 2020-12-16 23:27
`3.11.9-debian-10-r30` was just released with the fix, so I'll mark this issue as resolved.

**Closed by marcosbc** 2020-12-16 23:27 UTC
