### ISSUE TITLE
Cassandra exits on initialization without error

### ISSUE THREAD

**Issue by PedroD** [bitnami/bitnami-docker-cassandra#47] opened 2018-04-01 23:06 UTC
Dear bitnami team,

# General Info

**Docker:** Docker version 18.03.0-ce, build 0520e24

**OS:** Linux myserver-testbed 4.4.122-mainline-rev1 #1 SMP Sun Mar 18 10:44:19 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 16

# Problem

I have the following compose:

```
version: '2'
services:
    cassandra:
        image: 'bitnami/cassandra:3'
        labels:
          kompose.service.type: nodeport
        ports:
          - '7000:7000'
          - '9042:9042'
        volumes:
            - ./cassandra_persistence:/bitnami
        environment:
          - CASSANDRA_PASSWORD_SEEDER=yes
          - CASSANDRA_USER=cassandra
          - CASSANDRA_PASSWORD=cassandra
```

Note that I want to persist the data on disk in `./cassandra_persistence` (notice the `volumes` option). 

I then execute `docker-compose up` and Cassandra initializes correctly after about 60 seconds.
However, now if I do `docker-compose down` followed by `docker-compose up`, this will happen:

```
$ docker-compose up cassandra
Creating network "easywhateverrestapi_default" with the default driver
Creating easywhateverrestapi_cassandra_1
Attaching to easywhateverrestapi_cassandra_1
cassandra_1  |
cassandra_1  | Welcome to the Bitnami cassandra container
cassandra_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-cassandra
cassandra_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-cassandra/issues
cassandra_1  | Send us your feedback at containers@bitnami.com
cassandra_1  |
cassandra_1  | nami    INFO  Initializing cassandra
cassandra_1  | cassand INFO
cassandra_1  | cassand INFO  ########################################################################
cassandra_1  | cassand INFO   Installation parameters for cassandra:
cassandra_1  | cassand INFO     Persisted data and properties have been restored.
cassandra_1  | cassand INFO     Any input specified will not take effect.
cassandra_1  | cassand INFO   This installation requires no credentials.
cassandra_1  | cassand INFO  ########################################################################
cassandra_1  | cassand INFO
cassandra_1  | nami    INFO  cassandra successfully initialized
cassandra_1  | INFO  ==> Starting cassandra...
easywhateverrestapi_cassandra_1 exited with code 0
$
```

This issue only resolves itself if I run `rm -rf ./cassandra_persistence` (i.e. delete the persistence folder).

What is going on here?

Thanks

**Comment by juan131** [comment] 2018-04-02 09:40
Hi @PedroD 

I was unable to reproduce the issue... I just created the directory and run the commands you mentioned:

```
mkdir cassandra_persistence
docker-compose up
docker-compose down
docker-compose up
```

`docker-compose.yml` used:

```
version: '2'

services:
  cassandra:
    image: 'bitnami/cassandra:latest'
    ports:
      - '7000:7000'
      - '9042:9042'
    environment:
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - './cassandra_persistence:/bitnami'
```

First `docker-compose up`:

```
cassandra_1  | Welcome to the Bitnami cassandra container
cassandra_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-cassandra
cassandra_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-cassandra/issues
cassandra_1  | Send us your feedback at containers@bitnami.com
cassandra_1  |
cassandra_1  | nami    INFO  Initializing cassandra
cassandra_1  | cassand INFO  Starting Cassandra, this may take some time...
cassandra_1  | cassand INFO  Waiting for Cassandra to initialize, this may take some time...
cassandra_1  | cassand INFO  ==> Updating the password for the "cassandra" user...
cassandra_1  | cassand INFO
cassandra_1  | cassand INFO  ########################################################################
cassandra_1  | cassand INFO   Installation parameters for cassandra:
cassandra_1  | cassand INFO     Username: cassandra
cassandra_1  | cassand INFO     Password: **********
cassandra_1  | cassand INFO   (Passwords are not shown for security reasons)
cassandra_1  | cassand INFO  ########################################################################
cassandra_1  | cassand INFO
cassandra_1  | nami    INFO  cassandra successfully initialized
cassandra_1  | INFO  ==> Starting cassandra...
```

Second one:

```
cassandra_1  | Welcome to the Bitnami cassandra container
cassandra_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-cassandra
cassandra_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-cassandra/issues
cassandra_1  | Send us your feedback at containers@bitnami.com
cassandra_1  |
cassandra_1  | nami    INFO  Initializing cassandra
cassandra_1  | cassand INFO
cassandra_1  | cassand INFO  ########################################################################
cassandra_1  | cassand INFO   Installation parameters for cassandra:
cassandra_1  | cassand INFO     Persisted data and properties have been restored.
cassandra_1  | cassand INFO     Any input specified will not take effect.
cassandra_1  | cassand INFO   This installation requires no credentials.
cassandra_1  | cassand INFO  ########################################################################
cassandra_1  | cassand INFO
cassandra_1  | nami    INFO  cassandra successfully initialized
cassandra_1  | INFO  ==> Starting cassandra...
```

Did you run all the commands within the same directory?

**Comment by PedroD** [comment] 2018-04-02 10:47
Yes.

```
$ ls -lah
total 20K
drwxr-xr-x  4 root root 4.0K Apr  2 10:44 .
drwx------ 10 root root 4.0K Apr  2 10:41 ..
drwxr-xr-x  3 root root 4.0K Apr  2 10:42 cassandra_persistence
-rw-r--r--  1 root root 1.2K Apr  2 10:44 docker-compose.yaml
drwx------ 19  999 root 4.0K Apr  2 10:44 postgres_persistence

$ cat docker-compose.yaml
version: '2'
services:
    cassandra: # https://github.com/bitnami/bitnami-docker-cassandra/blob/master/3/docker-compose.yml
        image: 'bitnami/cassandra:3'
        labels:
          kompose.service.type: nodeport
        ports:
          - '7000:7000'
          - '9042:9042'
        volumes:
            - ./cassandra_persistence:/bitnami
        environment:
          - CASSANDRA_PASSWORD_SEEDER=yes
          - CASSANDRA_USER=cassandra
          - CASSANDRA_PASSWORD=cassandra
    redis: # https://github.com/bitnami/bitnami-docker-redis/blob/master/4.0/Dockerfile
        image: 'bitnami/redis:4.0'
        environment:
        # ALLOW_EMPTY_PASSWORD is recommended only for development.
        - ALLOW_EMPTY_PASSWORD=no
        - REDIS_PASSWORD=123456
        - REDIS_MASTER_PASSWORD=123456
        labels:
            kompose.service.type: nodeport
        ports:
        - '6379:6379'
    pgsql:
        image: 'postgres:10'
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=easywhatever
        volumes:
          - ./postgres_persistence:/var/lib/postgresql/data


$ docker-compose up
Creating network "lixo_default" with the default driver
Creating lixo_pgsql_1
Creating lixo_redis_1
Creating lixo_cassandra_1
Attaching to lixo_pgsql_1, lixo_redis_1, lixo_cassandra_1
pgsql_1      | 2018-04-02 10:45:52.668 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pgsql_1      | 2018-04-02 10:45:52.668 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pgsql_1      | 2018-04-02 10:45:52.674 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pgsql_1      | 2018-04-02 10:45:52.709 UTC [25] LOG:  database system was shut down at 2018-04-02 10:44:02 UTC
pgsql_1      | 2018-04-02 10:45:52.718 UTC [1] LOG:  database system is ready to accept connections
redis_1      |
redis_1      | Welcome to the Bitnami redis container
redis_1      | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis_1      | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis_1      | Send us your feedback at containers@bitnami.com
redis_1      |
cassandra_1  |
cassandra_1  | Welcome to the Bitnami cassandra container
cassandra_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-cassandra
cassandra_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-cassandra/issues
cassandra_1  | Send us your feedback at containers@bitnami.com
cassandra_1  |
redis_1      | nami    INFO  Initializing redis
redis_1      | redis   INFO  ==> Validating inputs...
redis_1      | redis   INFO
redis_1      | redis   INFO  ########################################################################
redis_1      | redis   INFO   Installation parameters for redis:
redis_1      | redis   INFO     Password: **********
redis_1      | redis   INFO   (Passwords are not shown for security reasons)
redis_1      | redis   INFO  ########################################################################
redis_1      | redis   INFO
redis_1      | nami    INFO  redis successfully initialized
redis_1      | INFO  ==> Starting redis...
redis_1      | 30:C 02 Apr 10:45:58.261 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1      | 30:C 02 Apr 10:45:58.262 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=30, just started
redis_1      | 30:C 02 Apr 10:45:58.262 # Configuration loaded
redis_1      |                 _._
redis_1      |            _.-``__ ''-._
redis_1      |       _.-``    `.  `_.  ''-._           Redis 4.0.9 (00000000/0) 64 bit
redis_1      |   .-`` .-```.  ```\/    _.,_ ''-._
redis_1      |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1      |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1      |  |    `-._   `._    /     _.-'    |     PID: 30
redis_1      |   `-._    `-._  `-./  _.-'    _.-'
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1      |  |    `-._`-._        _.-'_.-'    |           http://redis.io
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1      |  |    `-._`-._        _.-'_.-'    |
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1      |       `-._    `-.__.-'    _.-'
redis_1      |           `-._        _.-'
redis_1      |               `-.__.-'
redis_1      |
redis_1      | 30:M 02 Apr 10:45:58.264 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1      | 30:M 02 Apr 10:45:58.264 # Server initialized
redis_1      | 30:M 02 Apr 10:45:58.264 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1      | 30:M 02 Apr 10:45:58.264 * Ready to accept connections
cassandra_1  | nami    INFO  Initializing cassandra
cassandra_1  | cassand INFO
cassandra_1  | cassand INFO  ########################################################################
cassandra_1  | cassand INFO   Installation parameters for cassandra:
cassandra_1  | cassand INFO     Persisted data and properties have been restored.
cassandra_1  | cassand INFO     Any input specified will not take effect.
cassandra_1  | cassand INFO   This installation requires no credentials.
cassandra_1  | cassand INFO  ########################################################################
cassandra_1  | cassand INFO
cassandra_1  | nami    INFO  cassandra successfully initialized
cassandra_1  | INFO  ==> Starting cassandra...
lixo_cassandra_1 exited with code 0
```

These are the exact conditions I am running this.

**Comment by PedroD** [comment] 2018-04-02 10:54
Sometimes if I clear the persistence folder cassandra hangs here without exiting:

```
$ docker-compose up
Creating network "lixo_default" with the default driver
Creating lixo_cassandra_1
Attaching to lixo_cassandra_1
cassandra_1  |
cassandra_1  | Welcome to the Bitnami cassandra container
cassandra_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-cassandra
cassandra_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-cassandra/issues
cassandra_1  | Send us your feedback at containers@bitnami.com
cassandra_1  |
cassandra_1  | nami    INFO  Initializing cassandra
cassandra_1  | cassand INFO  Starting Cassandra, this may take some time...
cassandra_1  | cassand INFO  Waiting for Cassandra to initialize, this may take some time...
cassandra_1  | cassand INFO  ==> Updating the password for the "cassandra" user...
cassandra_1  | cassand INFO
cassandra_1  | cassand INFO  ########################################################################
cassandra_1  | cassand INFO   Installation parameters for cassandra:
cassandra_1  | cassand INFO     Username: cassandra
cassandra_1  | cassand INFO     Password: **********
cassandra_1  | cassand INFO   (Passwords are not shown for security reasons)
cassandra_1  | cassand INFO  ########################################################################
cassandra_1  | cassand INFO
cassandra_1  | nami    INFO  cassandra successfully initialized
cassandra_1  | INFO  ==> Starting cassandra...
cassandra_1  |

```

**Comment by PedroD** [comment] 2018-04-02 17:40
It sound similar to this issue: https://support.datastax.com/hc/en-us/articles/204226099-On-startup-cassandra-exits-without-error-or-creating-logs

**Comment by PedroD** [comment] 2018-04-02 22:39
I am not being able to activate the DEBUG logs for this container...

**Comment by PedroD** [comment] 2018-04-03 00:04
Could this be the issue?

```
INFO  ==> Starting cassandra...
[WARN  tini (306)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:780) ~[apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:667) ~[apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:613) ~[apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:379) [apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:602) [apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:691) [apache-cassandra-3.11.2.jar:3.11.2]
```

**Comment by PedroD** [comment] 2018-04-03 00:53
I was finally able to collect some DEBUG logs:

[First run, when there is no persisted data.](https://www.dropbox.com/s/2s08z8nnk2gszak/FIRST_RUN.log?dl=1)

[Second run, when there is persisted data and Cassandra starts having errors.](https://www.dropbox.com/s/8ky9ss107fltdfr/SECOND_RUN_ERROR.log?dl=1)

Although when I capture these logs Cassandra keeps running, which is strange, given that when I don't capture the logs Cassandra dies and consequently the container exits. The way I capture the logs might have affected something, but still there are some errors there.

**Comment by juan131** [comment] 2018-04-09 16:18
Hi @PedroD 

It seems you're using different ownership/permissions for the persistence directories:

```
drwxr-xr-x  3 root root 4.0K Apr  2 10:42 cassandra_persistence
-rw-r--r--  1 root root 1.2K Apr  2 10:44 docker-compose.yaml
drwx------ 19  999 root 4.0K Apr  2 10:44 postgres_persistence
```

What user are you using to run `docker-compose up`?

**Comment by ehsannm** [comment] 2018-04-18 08:07
I have the same issue, it is only happens on ubuntu 16, no problem in Mac OS

**Comment by ehsannm** [comment] 2018-04-18 08:15
Error executing 'postInstallation': File /opt/bitnami/cassandra/conf/cassandra.yaml did not match any of the provided substitutions

**Comment by juan131** [comment] 2018-04-19 15:38
Hi @ehsannm 

That looks like a different issue. It looks like an issue when Nami configures the configuration file by substituting some regexps with the right values.

Could you please share the logs obtained when running the container using the env. variable **NAMI_DEBUG="--log-level=trace"**

**Comment by marcosbc** [comment] 2018-07-27 11:20
Hi @ehsannm, could you provide more information on how to reproduce this issue on our side?

In your previous comment, you mentioned you got the following error:

```
Error executing 'postInstallation': File /opt/bitnami/cassandra/conf/cassandra.yaml did not match any of the provided substitutions
```

Is this issue happening consistently with a clean docker-compose environment (e.g. with a clean volume)? If so, could you send us a `docker-compose.yml` where that error happens?

If the issue only happens in your existing container (not in new ones), it is most probably due to a corrupt database.
You could debug this by running Bash (instead of Cassandra), and then starting Cassandra in order to see what errors you get (supposing your Docker volume is named `db-cass_data`):

```
$ docker commit db-cass_1 mycassandra
$ docker run --mount source=db-cass_data,target=/bitnami -ti --rm mycassandra /bin/bash
```

Now, inside the container, run the following commands for starting Cassandra, checking the logs for any error after it's started:

```
$ nami start cassandra
$ more /opt/bitnami/cassandra/logs/cassandra.log
```

**Comment by ehsannm** [comment] 2018-07-27 12:00
Hi @marcosbc 
No this does not happen when i use a clean volume. The first time I run it everything is ok. But the problem is when I restart the docker. It exists with status 0, which is translated by docker as a successful exit.

I had the same issue with Redis image to, but I managed to fix it by creating the volume folder myself instead of letting docker-compose make it for me. Since when docker-compose creates a volume at the start up it makes the owner root.

For Cassandra i did the same, but cassandra creates some folders inside the volume. The weird thing is some of them are owned by 'root' and some with my user 'ehsan'

```
drwxrwxr-x 4 ehsan ehsan 4096 Jul 27 11:43 ./
drwxrwxr-x 3 ehsan ehsan 4096 Jul 27 11:43 ../
drwxr-xr-x 3 root  root  4096 Jul 27 11:43 conf/
drwxr-xr-x 6 ehsan ehsan 4096 Jul 27 11:43 data/
-rw-r--r-- 1 root  root     0 Jul 27 11:43 .initialized
```


Somehow, I am thinking this is not normal :-/

**Comment by marcosbc** [comment] 2018-07-31 10:49
Hi @ehsannm, we're still unable to reproduce your issue.

We did the following, in Docker for Mac, using the `docker-compose.yml` file below:

```
version: '2'
services:
    cassandra:
        image: 'bitnami/cassandra:latest'
        labels:
          kompose.service.type: nodeport
        ports:
          - '7000:7000'
          - '9042:9042'
        volumes:
            - ./cassandra_persistence:/bitnami
        environment:
          - CASSANDRA_USER=cassandra
          - CASSANDRA_PASSWORD=cassandra
```

- Start Cassandra with `docker-compose up` and wait some minutes (at least so Cassandra is initialized).
- Stop Cassandra with `docker stop sp_cassandra_1` and let it be stopped for some minutes.
- Start Cassandra again with `docker-compose start sp_cassandra_1`. It works perfectly.

Could you provide the following?

- `docker-compose.yml` with steps to reproduce the issue in an isolated environment.
- Connect to the failed container like we mentioned below, and start Cassandra manually. What do you get? Do you see any errors in the logs? Find the quoted steps below:

>  You could debug this by running Bash (instead of Cassandra), and then starting Cassandra in order to see what errors you get (supposing your Docker volume is named db-cass_data):
>
>    $ docker commit db-cass_1 mycassandra
>    $ docker run --mount source=db-cass_data,target=/bitnami -ti --rm mycassandra /bin/bash
>
>Now, inside the container, run the following commands for starting Cassandra, checking the logs for any error after it's started:
>
>    $ nami start cassandra
>    $ more /opt/bitnami/cassandra/logs/cassandra.log

**Comment by kayvannm** [comment] 2018-08-02 13:06
Hi @marcosbc , i did what you told ,
this is our yml file : 
```yaml
version: '2'
services:
  db:
    restart: on-failure
    image: bitnami/cassandra:latest
    volumes:
      - ./vol/:/bitnami
    network_mode: "host"
    ports:
      - 7000:7000
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=some-cluster
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
```
i did what you told in the last comment, but log was empty and after 12 minutes this error came up
```bash
db_1  | nami    ERROR Unable to start com.bitnami.cassandra: /opt/bitnami/cassandra/bin/cassandra: 215: exec: java: not found
```
here is steps to reproduce:

- create a directory in / named "db-cass" and here is "ls -alh" for directory:

```bash
drwxr--r--   4 devops-adm devops-adm  4096 Aug  2 07:11 db-cass/
```
- then create a vol directory in "/db-cass" and here are permissions:

```bash
drwxr--r--  3 devops-adm devops-adm 4096 Aug  2 07:32 ./
drwxr-xr-x 24 root        root        4096 Jul 27 16:12 ../
-rw-rw-r--  1 devops-adm devops-adm  435 Aug  2 06:56 docker-compose.yml
drwxr--r--  3 devops-adm devops-adm 4096 Aug  2 07:03 vol/
```
when we `docker-compose up` with devops-adm following directories will be created in vol/ :
```bash
drwxr--r-- 3 devops-adm devops-adm 4096 Aug  2 07:03 ./
drwxr--r-- 3 devops-adm devops-adm 4096 Aug  2 07:32 ../
drwxr-xr-x 4 root        root        4096 Aug  2 07:03 cassandra/
```
and in cassandra directory : 
```bash
drwxr-xr-x 4 root        root      4096 Aug  2 07:03 ./
drwxr--r-- 3 devops-adm devops-adm 4096 Aug  2 07:03 ../
drwxr-xr-x 3 root        root     4096 Aug  2 07:03 conf/
drwxr-xr-x 6 chikiw     chikiw    4096 Aug  2 07:03 data/
-rw-r--r-- 1 root        root      0 Aug  2 07:03 .initialized
```
and i think the problem is the "chikiw" user, chikiw is another sudoer user in our environment.
i tested this on another machine and the results was the same , and in that machine the vol/cassandra/data was owened by another sudoer user.

**Comment by marcosbc** [comment] 2018-08-03 09:58
Hi @kayvannm, thanks for the detailed steps. We were able to reproduce this.

It happens because Cassandra runs as a non-root user (uid 1001), and is unable to write to `/bitnami` at runtime.
There are two ways to fix this:

- Change ownership to `1001:1001` to the `vol` directory before running the container.
- Create a dummy container changes the ownership automatically for you before running the container, e.g.:

```
version: '2'
services:
  fix-cassandra-permissions:
    image: bitnami/cassandra:latest
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - ./vol/:/bitnami
  db:
    depends_on:
      - fix-cassandra-permissions
    restart: on-failure
    image: bitnami/cassandra:latest
    volumes:
      - ./vol/:/bitnami
    network_mode: "host"
    ports:
      - 7000:7000
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=some-cluster
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
```

Fixing this depends on [this Docker issue](https://github.com/moby/moby/issues/2259), and you can see [here](https://github.com/bitnami/bitnami-docker-suitecrm/issues/72) that it is not specific to the Bitnami Cassandra container.

Let us know if this worked for you.

**Comment by kayvannm** [comment] 2018-08-03 14:16
@marcosbc hey again, i check that, it will not solve the problem, but this helped that cassandra uses a 
non-root user. the ownership of /db-cass ( directory included docker-compose.yml ) must be 1001:1001.

**Comment by marcosbc** [comment] 2018-08-03 14:44
Hi @kayvannm, sorry but it is not clear what exact issue you are facing. Isn't it the one I've added below?

    Error executing 'postInstallation': File /opt/bitnami/cassandra/conf/cassandra.yaml did not match any of the provided substitutions

That is the issue we got in our Docker environment, with the Docker Compose file and instructions you provided. The way to fix that error is by ensuring Cassandra has permissions to write in the data directory.

If you get that error in an already initialized Cassandra instance, and you don't have any relevant data, you can clean it and try again (with the docker-compose we provided in our previous comment):

    rm -rf /db-cass/vol
    docker-compose up

**Comment by ehsannm** [comment] 2018-08-03 19:31
Thanks @marcosbc, your solution does work. However, I hope docker team fix the issue.

**Comment by marcosbc** [comment] 2018-08-06 07:46
Thanks for letting us know @ehsannm! Since you were able to resolve your issues with the image, I'm going to close this ticket.

**Closed by marcosbc** 2018-08-06 07:46 UTC
